"""fase 15: servicos avulsos + vinculo despesas/recebimentos

Revision ID: 5cad36f78dbb
Revises: ea46e9dd6bd2
Create Date: 2026-07-06 14:08:13.931099

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5cad36f78dbb'
down_revision: Union[str, None] = 'ea46e9dd6bd2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('servicos',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('descricao', sa.Text(), nullable=False),
    sa.Column('cliente', sa.String(), nullable=True),
    sa.Column('valor', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('data_inicio', sa.Date(), nullable=False),
    sa.Column('data_finalizacao', sa.Date(), nullable=True),
    sa.Column('obs', sa.Text(), nullable=True),
    sa.Column('fechamento_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['fechamento_id'], ['fechamentos.id'], name=op.f('fk_servicos_fechamento_id_fechamentos'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_servicos'))
    )
    with op.batch_alter_table('servicos', schema=None) as batch_op:
        batch_op.create_index('ix_servicos_status', ['status'], unique=False)

    op.create_table('servico_entradas',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('servico_id', sa.Integer(), nullable=False),
    sa.Column('data', sa.Date(), nullable=False),
    sa.Column('descricao', sa.Text(), nullable=False),
    sa.ForeignKeyConstraint(['servico_id'], ['servicos.id'], name=op.f('fk_servico_entradas_servico_id_servicos'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_servico_entradas'))
    )
    with op.batch_alter_table('servico_entradas', schema=None) as batch_op:
        batch_op.create_index('ix_servico_entradas_servico_id_data', ['servico_id', 'data'], unique=False)

    op.create_table('servico_trabalhos',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('entrada_id', sa.Integer(), nullable=False),
    sa.Column('ajudante_id', sa.Integer(), nullable=True),
    sa.Column('ajudante_nome', sa.String(), nullable=False),
    sa.Column('horas', sa.Numeric(precision=5, scale=1), nullable=False),
    sa.Column('valor', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('origem', sa.String(), nullable=False),
    sa.Column('proprio', sa.Boolean(), server_default=sa.false(), nullable=False),
    sa.ForeignKeyConstraint(['ajudante_id'], ['ajudantes.id'], name=op.f('fk_servico_trabalhos_ajudante_id_ajudantes'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['entrada_id'], ['servico_entradas.id'], name=op.f('fk_servico_trabalhos_entrada_id_servico_entradas'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_servico_trabalhos'))
    )
    with op.batch_alter_table('despesas', schema=None) as batch_op:
        batch_op.add_column(sa.Column('servico_id', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('servico_nome', sa.String(), nullable=True))
        batch_op.create_foreign_key(batch_op.f('fk_despesas_servico_id_servicos'), 'servicos', ['servico_id'], ['id'], ondelete='SET NULL')

    with op.batch_alter_table('recebimentos', schema=None) as batch_op:
        batch_op.add_column(sa.Column('servico_id', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('servico_nome', sa.String(), nullable=True))
        batch_op.create_foreign_key(batch_op.f('fk_recebimentos_servico_id_servicos'), 'servicos', ['servico_id'], ['id'], ondelete='SET NULL')

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('recebimentos', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('fk_recebimentos_servico_id_servicos'), type_='foreignkey')
        batch_op.drop_column('servico_nome')
        batch_op.drop_column('servico_id')

    with op.batch_alter_table('despesas', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('fk_despesas_servico_id_servicos'), type_='foreignkey')
        batch_op.drop_column('servico_nome')
        batch_op.drop_column('servico_id')

    op.drop_table('servico_trabalhos')
    with op.batch_alter_table('servico_entradas', schema=None) as batch_op:
        batch_op.drop_index('ix_servico_entradas_servico_id_data')

    op.drop_table('servico_entradas')
    with op.batch_alter_table('servicos', schema=None) as batch_op:
        batch_op.drop_index('ix_servicos_status')

    op.drop_table('servicos')
    # ### end Alembic commands ###
