"""inicial: modelos da secao 4

Revision ID: c86f134d7b74
Revises: 
Create Date: 2026-07-03 13:18:19.467394

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c86f134d7b74'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('ajudantes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nome', sa.String(), nullable=False),
    sa.Column('telefone', sa.String(), nullable=True),
    sa.Column('valor_hora_padrao', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('obs', sa.Text(), nullable=True),
    sa.Column('ativo', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_ajudantes'))
    )
    op.create_table('config',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nome_exibicao', sa.String(), nullable=False),
    sa.Column('telefone', sa.String(), nullable=True),
    sa.Column('logo_filename', sa.String(), nullable=True),
    sa.Column('prox_fec', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_config'))
    )
    op.create_table('fechamentos',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('numero', sa.String(), nullable=False),
    sa.Column('data_geracao', sa.DateTime(), nullable=False),
    sa.Column('periodo_de', sa.Date(), nullable=False),
    sa.Column('periodo_ate', sa.Date(), nullable=False),
    sa.Column('total_devido', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('total_adiantado', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('saldo', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('obs', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_fechamentos')),
    sa.UniqueConstraint('numero', name=op.f('uq_fechamentos_numero'))
    )
    op.create_table('repasse_entradas',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('data', sa.Date(), nullable=False),
    sa.Column('valor', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('obs', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_repasse_entradas'))
    )
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(), nullable=False),
    sa.Column('hashed_password', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_users'))
    )
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_users_username'), ['username'], unique=True)

    op.create_table('maquinas',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nome', sa.String(), nullable=False),
    sa.Column('cliente', sa.String(), nullable=False),
    sa.Column('empreita', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('data_inicio', sa.Date(), nullable=False),
    sa.Column('data_finalizacao', sa.Date(), nullable=True),
    sa.Column('obs', sa.Text(), nullable=True),
    sa.Column('fechamento_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['fechamento_id'], ['fechamentos.id'], name=op.f('fk_maquinas_fechamento_id_fechamentos'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_maquinas'))
    )
    with op.batch_alter_table('maquinas', schema=None) as batch_op:
        batch_op.create_index('ix_maquinas_status', ['status'], unique=False)

    op.create_table('diario_entradas',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('maquina_id', sa.Integer(), nullable=False),
    sa.Column('data', sa.Date(), nullable=False),
    sa.Column('descricao', sa.Text(), nullable=False),
    sa.ForeignKeyConstraint(['maquina_id'], ['maquinas.id'], name=op.f('fk_diario_entradas_maquina_id_maquinas'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_diario_entradas'))
    )
    with op.batch_alter_table('diario_entradas', schema=None) as batch_op:
        batch_op.create_index('ix_diario_entradas_maquina_id_data', ['maquina_id', 'data'], unique=False)

    op.create_table('recebimentos',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('tipo', sa.String(), nullable=False),
    sa.Column('data', sa.Date(), nullable=False),
    sa.Column('valor', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('maquina_id', sa.Integer(), nullable=True),
    sa.Column('maquina_nome', sa.String(), nullable=True),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('fechamento_id', sa.Integer(), nullable=True),
    sa.Column('obs', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['fechamento_id'], ['fechamentos.id'], name=op.f('fk_recebimentos_fechamento_id_fechamentos'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['maquina_id'], ['maquinas.id'], name=op.f('fk_recebimentos_maquina_id_maquinas'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_recebimentos'))
    )
    with op.batch_alter_table('recebimentos', schema=None) as batch_op:
        batch_op.create_index('ix_recebimentos_tipo_status', ['tipo', 'status'], unique=False)

    op.create_table('diario_trabalhos',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('entrada_id', sa.Integer(), nullable=False),
    sa.Column('ajudante_id', sa.Integer(), nullable=True),
    sa.Column('ajudante_nome', sa.String(), nullable=False),
    sa.Column('horas', sa.Numeric(precision=5, scale=1), nullable=False),
    sa.Column('valor', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('origem', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['ajudante_id'], ['ajudantes.id'], name=op.f('fk_diario_trabalhos_ajudante_id_ajudantes'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['entrada_id'], ['diario_entradas.id'], name=op.f('fk_diario_trabalhos_entrada_id_diario_entradas'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_diario_trabalhos'))
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('diario_trabalhos')
    with op.batch_alter_table('recebimentos', schema=None) as batch_op:
        batch_op.drop_index('ix_recebimentos_tipo_status')

    op.drop_table('recebimentos')
    with op.batch_alter_table('diario_entradas', schema=None) as batch_op:
        batch_op.drop_index('ix_diario_entradas_maquina_id_data')

    op.drop_table('diario_entradas')
    with op.batch_alter_table('maquinas', schema=None) as batch_op:
        batch_op.drop_index('ix_maquinas_status')

    op.drop_table('maquinas')
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_users_username'))

    op.drop_table('users')
    op.drop_table('repasse_entradas')
    op.drop_table('fechamentos')
    op.drop_table('config')
    op.drop_table('ajudantes')
    # ### end Alembic commands ###
