"""fase 12d: proprio no diario e tabela despesas

Revision ID: ea46e9dd6bd2
Revises: c86f134d7b74
Create Date: 2026-07-03 18:48:29.010934

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ea46e9dd6bd2'
down_revision: Union[str, None] = 'c86f134d7b74'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('despesas',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('data', sa.Date(), nullable=False),
    sa.Column('valor', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('categoria', sa.String(), nullable=False),
    sa.Column('descricao', sa.Text(), nullable=True),
    sa.Column('maquina_id', sa.Integer(), nullable=True),
    sa.Column('maquina_nome', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['maquina_id'], ['maquinas.id'], name=op.f('fk_despesas_maquina_id_maquinas'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_despesas'))
    )
    with op.batch_alter_table('despesas', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_despesas_data'), ['data'], unique=False)

    with op.batch_alter_table('diario_trabalhos', schema=None) as batch_op:
        batch_op.add_column(sa.Column('proprio', sa.Boolean(), server_default=sa.text('0'), nullable=False))

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('diario_trabalhos', schema=None) as batch_op:
        batch_op.drop_column('proprio')

    with op.batch_alter_table('despesas', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_despesas_data'))

    op.drop_table('despesas')
    # ### end Alembic commands ###
